const riReact=Spicetify.React,riEl=riReact.createElement;
function RadioPlaylist(){
 const [countries,setCountries]=riReact.useState([]),[country,setCountry]=riReact.useState(null),[countryQuery,setCountryQuery]=riReact.useState(''),[stations,setStations]=riReact.useState([]),[page,setPage]=riReact.useState(0),[hasMore,setHasMore]=riReact.useState(false),[loading,setLoading]=riReact.useState(false),[error,setError]=riReact.useState(''),[query,setQuery]=riReact.useState(''),[ordering,setOrdering]=riReact.useState(false),[dragId,setDragId]=riReact.useState(null);
 const [playerState,setPlayerState]=riReact.useState(()=>window.RadioItalianePlayer?.getState()||{station:null,status:'Scegli una radio',playing:false});
 const current=playerState.station,status=playerState.status,playing=playerState.playing,api=path=>RI_BRIDGE.base+path+(path.includes('?')?'&':'?')+'key='+encodeURIComponent(RI_BRIDGE.key),orderKey=code=>'ri-station-order:'+code,hasLogo=station=>Boolean(station.logo&&!/placeholder/i.test(station.logo));
 function applyOrder(list,code){const base=list.map((station,index)=>({station,index})).sort((a,b)=>Number(hasLogo(b.station))-Number(hasLogo(a.station))||a.index-b.index).map(item=>item.station);try{const saved=JSON.parse(localStorage.getItem(orderKey(code))||'[]');if(Array.isArray(saved)&&saved.length){const byId=new Map(base.map(station=>[station.id,station]));return[...saved.map(id=>byId.get(id)).filter(Boolean),...base.filter(station=>!saved.includes(station.id))]}}catch{}return base}
 function publish(next){setStations(next);window.RI_STATIONS=next;window.dispatchEvent(new CustomEvent('ri-stations-changed'))}
 riReact.useEffect(()=>{fetch(api('/countries')).then(r=>r.json()).then(setCountries).catch(()=>setError('Impossibile caricare le nazioni'));return window.RadioItalianePlayer?.subscribe(setPlayerState)},[]);
 riReact.useEffect(()=>{if(!countries.length)return;const sync=entry=>{const location=entry?.location||entry||Spicetify.Platform.History.location,params=new URLSearchParams(location?.search||''),code=params.get('country');if(!code){setCountry(null);publish([]);setPage(0);setHasMore(false);setOrdering(false);return}const selected=countries.find(c=>c.code===code);if(selected)loadCountry(selected)};sync(Spicetify.Platform.History.location);return Spicetify.Platform.History.listen(sync)},[countries]);
 async function loadCountry(selected,nextPage=1,append=false){setLoading(true);setError('');try{const response=await fetch(api('/catalog/'+selected.code+'?page='+nextPage),{cache:'no-store'});if(!response.ok)throw Error();const data=await response.json(),combined=append?[...stations,...data.stations]:data.stations,next=applyOrder(combined,selected.code);setCountry(selected);publish(next);setPage(nextPage);setHasMore(data.hasMore);setQuery('')}catch{setError('Non riesco a caricare le radio di questa nazione. Riprova.')}finally{setLoading(false)}}
 function chooseCountry(selected){Spicetify.Platform.History.push('/radio-italiane?country='+encodeURIComponent(selected.code))}
 function moveStation(fromId,toId){if(!fromId||fromId===toId)return;const next=[...stations],from=next.findIndex(s=>s.id===fromId),to=next.findIndex(s=>s.id===toId);if(from<0||to<0)return;const[moved]=next.splice(from,1);next.splice(to,0,moved);localStorage.setItem(orderKey(country.code),JSON.stringify(next.map(s=>s.id)));publish(next);setDragId(null)}
 function resetOrder(){localStorage.removeItem(orderKey(country.code));publish(applyOrder(stations,country.code));setOrdering(false)}
 function play(station){if(playing&&current?.id===station?.id){stop();return}window.RadioItalianePlayer?.play(station)}function stop(){window.RadioItalianePlayer?.stop()}function playIcon(on){return riEl('span',{className:'ri-control-icon '+(on?'ri-pause-icon':'ri-play-icon'),'aria-hidden':'true'})}function logo(s){return hasLogo(s)?api('/logo/'+encodeURIComponent(s.id))+'&v=6':window.RI_COVER}
 const rows=stations.filter(s=>s.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())),visibleCountries=countries.filter(c=>c.name.toLocaleLowerCase().includes(countryQuery.trim().toLocaleLowerCase()));
 if(!country)return riEl('main',{className:'ri-app ri-world'},riEl('header',{className:'ri-hero'},riEl('img',{className:'ri-cover',src:window.RI_COVER,alt:'Radio dal mondo'}),riEl('div',null,riEl('p',{className:'ri-eyebrow'},'RADIO DAL MONDO'),riEl('h1',null,'Che radio vuoi sentire?'),riEl('p',null,'Scegli una nazione per caricare le sue stazioni radio.'))),riEl('div',{className:'ri-country-search'},riEl('input',{type:'search',placeholder:'Cerca una nazione…','aria-label':'Cerca una nazione',value:countryQuery,onChange:e=>setCountryQuery(e.target.value),autoFocus:true}),riEl('span',null,visibleCountries.length+' nazioni')),error&&riEl('p',{className:'ri-error'},error),riEl('section',{className:'ri-country-grid','aria-label':'Scegli la nazione'},...visibleCountries.map(c=>riEl('button',{key:c.code,className:'ri-country',onClick:()=>chooseCountry(c)},riEl('img',{className:'ri-flag',src:api('/flag/'+c.code),alt:'Bandiera '+c.name}),riEl('strong',null,c.name)))),!visibleCountries.length&&riEl('p',{className:'ri-empty'},'Nessuna nazione trovata.'));
 return riEl('main',{className:'ri-app'+(ordering?' ri-ordering':'')},riEl('header',{className:'ri-hero'},riEl('img',{className:'ri-cover',src:window.RI_COVER,alt:'Radio dal mondo'}),riEl('div',null,riEl('p',{className:'ri-eyebrow'},country.flag+' RADIO DAL MONDO'),riEl('h1',null,'Radio '+country.name),riEl('p',null,'Le stazioni in diretta del paese selezionato.'),riEl('button',{className:'ri-change-country',onClick:()=>Spicetify.Platform.History.goBack()},'← Cambia nazione'))),riEl('div',{className:'ri-tools'},riEl('div',{className:'ri-order-tools'},riEl('button',{className:'ri-order-toggle','aria-pressed':ordering,onClick:()=>setOrdering(!ordering)},ordering?'Fine':'Riordina radio'),riEl('button',{className:'ri-order-reset',onClick:resetOrder},'Ripristina ordine')),riEl('span',null,stations.length+' stazioni caricate'),riEl('input',{type:'search',placeholder:'Cerca radio…','aria-label':'Cerca radio',value:query,onChange:e=>setQuery(e.target.value)})),riEl('div',{className:'ri-player','aria-live':'polite'},riEl('button',{disabled:!current,'aria-label':playing?'Metti in pausa la radio':'Riproduci radio',onClick:()=>playing?stop():current&&play(current)},playIcon(playing)),riEl('div',null,riEl('strong',null,current?current.name:'Pronto ad ascoltare?'),riEl('p',null,status))),error&&riEl('p',{className:'ri-error'},error),riEl('section',{className:'ri-station-grid','aria-label':'Stazioni radio'},...rows.map(s=>riEl('article',{key:s.id,className:'ri-station-card '+(current?.id===s.id?'ri-active ':'')+(dragId===s.id?'ri-dragging':''),draggable:ordering,onDragStart:()=>setDragId(s.id),onDragEnd:()=>setDragId(null),onDragOver:e=>ordering&&e.preventDefault(),onDrop:e=>{e.preventDefault();moveStation(dragId,s.id)}},ordering&&riEl('span',{className:'ri-drag-handle','aria-hidden':'true'},'⋮⋮'),riEl('button',{className:'ri-logo-button','aria-label':ordering?'Sposta '+s.name:'Ascolta '+s.name,onClick:()=>!ordering&&play(s)},riEl('img',{src:logo(s),alt:'Logo '+s.name,loading:'lazy',onError:e=>{e.currentTarget.onerror=null;e.currentTarget.src=window.RI_COVER}}),riEl('span',{className:'ri-card-play'},playIcon(current?.id===s.id&&playing))),riEl('div',{className:'ri-card-copy'},riEl('strong',null,s.name),riEl('small',null,current?.id===s.id?status:'Radio · In diretta'))))),!rows.length&&!loading&&riEl('p',{className:'ri-empty'},'Nessuna radio trovata.'),hasMore&&riEl('button',{className:'ri-load-more',disabled:loading,onClick:()=>loadCountry(country,page+1,true)},loading?'Caricamento…':'Carica altre radio'),loading&&riEl('p',{className:'ri-loading'},'Caricamento delle radio…'));
}
function render(){return riEl(RadioPlaylist)}
